name: Update champions database
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3.1.2
        with:
          github_token: ${{secrets.GH_TOKEN}}
          workflow: publish_u.gg.yml
          workflow_search: true
          workflow_conclusion: success
          name: packages
          path: actions
          if_no_artifact_found: fail
          repo: cangzhang/champ-r


      - name: Cleanup
        run: rm actions/u.gg/index.json actions/u.gg/package.json
      
      - name: Execute python
        uses: actions/setup-python@v5
        with:
            python-version: '3.10' 
      - run: python actions/item_builder.py

      - name: Extract and cleanup
        run: |
          mv actions/u.gg/* .
          rm -r actions/u.gg

      - name: Configure Git
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "bot: update champions database"
          git push origin ${{ github.event.inputs.branch_or_tag }}
